version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: driverall-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: driver
      MONGO_INITDB_ROOT_PASSWORD: driverpass
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: driverall-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://driver:driverpass@mongodb:27017/driverall-db?authSource=admin
      JWT_SECRET: benimsekretkey123
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "server.js"]

volumes:
  mongo_data:
